[[redirects]]
from = "/*"
to = "/"
status = 200
[[headers]]
[headers.values]
for = "/*"
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
